### PR TITLE
My initial attempt to merge a branch

### PR DESCRIPTION
**Pull request by tnakamot**
This is my first attempt to merge a branch to master.

### CODE REVIEW

**Comment by jasonweiss** [comment]
The viewing mode assembly was for switching between science and pupil viewing mode.  this isn't related to the cold stop, right?

**Comment by jasonweiss** [comment]
I'm ok with all of the other changes.

**Comment by edwardchapin** [comment]
Just a reminder that I have some pending questions with systems engineering / TMT regarding the structure of the up-stream (TMT-hosted) master model repository. I'm still hoping that they might use a monolithic repository instead of a per-subsystem submodule style. Regardless, we can use this repository for now to coordinate our efforts and we can figure out how to merge our stuff with theirs later.

Also, we should get the current iteration of the relevant Word document ICD under change control, then commit a literal translation of that document into model files, and then start diverging from that in separate pull requests.

Both of these points only become relevant when we get around to issuing TMT pull request at some point.

**Comment by jasonweiss** [comment]
i actually think i like having the submodules, since then we only need to worry about the subsystems we interface with, no?

**Comment by edwardchapin** [comment]
My main argument for a monolothic repository is that it's easier to mimic the workflow that we use to write the ICDs. Basically, two subsystem devs decide on some changes, and one of them actually does the work (i.e., making the related changes to both sides of the interface). If we do this in a single repository, then, for example, both the IRIS and TCS (or whatever) changes can appear in a single branch and pull request, making the history/logic much clearer. Otherwise we will often need to issue multiple pull requests for related changes (and of course, work with multiple repositories). 

The other thing is that, for any case in which changes to two subsystems are required, as soon as the first pull request is acted upon, the master branch will be in a broken state until the second subsystem pull request is applied. Alternatively, if everything happens in one branch in a monolithic repo, you avoid having a broken "released" set of ICDs.

It's perhaps mildly irritating seeing all of the subsystems you don't care about in the same repo, but I think it's a small price to pay for a simpler workflow.

Having said all of this, I don't think they're convinced, and I'm expecting they will want to stick with the separate repos :)

**Comment by tnakamot** [comment]
Jason, thank you for checking my commits.

> The viewing mode assembly was for switching between science and pupil viewing mode. this isn't related to the cold stop, right?

Sorry, my commit message of d28edee40d3e8b10917705acde5ae1a42d644727 was not appropriate. I meant only one assembly is enough for pupil viewing mode.

The actual behavior of pupil viewing mode is not well considered yet, but as you mentioned, one major role is to switch between science and pupil viewing mode by inserting or retracting one dedicated pick-off mirror. This assembly may additionally control a detector controller for pupil viewing through an HCD, but this is TBD. There is another option to newly define a separate assembly called "pupil detector assembly" to control the detector controller

In actual cold mask calibration for which pupil viewing mode is used, there should be some coordination among different assemblies. The final product of this calibration would be a table which maps (pupil rotation angle, instrument rotator angle) to (X, Y, theta). Pupil rotation would be done by using NSCU or even telescope.  Appropriate X, Y and theta position of the cold stop will be determined by taking images in the pupil viewing mode, but coordination among NSCU, telescope, instrument rotator, cold stop and pupil viewing mode assembly shall be done in higher level because it spans to another subsystem outside IRIS.

**Comment by tnakamot** [comment]
Ed,

> Regardless, we can use this repository for now to coordinate our efforts and we can figure out how to merge our stuff with theirs later.

Merging our stuff to theirs is possible if you don't need commit logs. Even if we want to keep the commit logs in the monolithic TMT repository, it might be possible but we have to check.

My commits in this pull request were made in IRIS's private git repository where not only model files are stored, but also other source files. It was a complete different repository, and I made some changes there. Then, I extracted all my changes using "git format-patch" command which generates a sequence of patches with commit message, and applied those patches to this repository using "git am" command with an appropriate "-p" option to omit a top directory from the path recorded in the patches. Actually, I applied those patches in sometime in July, but the original commit messages and the original date of commits are retained. For example, the patch corresponding to commit d28edee has a date 15th June JST, which was the date & time I made this change for the original IRIS's private repository, while I applied this patch to this repository after that date.

The reverse operation would need "--directory" option to append a top directory name to the path, though I've not used this option so far. In addition, I am not also sure how "git format-patch" and "git am" work if there are merges of different branches.

**Comment by edwardchapin** [comment]
Hi - oh I see, yes, you can certainly use git patches to fish your changes out of the old IRIS repository (I was more thinking along the lines of simply copying and pasting the files into whatever new repository we're going to use). You could also do things like create a git filter branch in the original repository (to remove all of the source code not related to model files), and then set the old repo as a remote for the new one, and merge that filter branch into the new repository. However, that solution might be even trickier to wrap your brain around than the patch method you used!

 I suspect history isn't all that important at this stage of development :) Even when we do get the full process worked out, we may not want to send a lot of mini-commits to TMT; we may possibly do the work in a dev branch, and then create a pull request branch (to send to them) that squashes all of the commits into one (e.g., git merge --squash).

All details we can experiment with at some point in the future...

**Comment by tnakamot** [comment]
I thought sometimes version history matters not to go back and forth between two possible design options, but, as you said, in the initial development stage, that is not that important. Priority would be to fill out model files first, then we can start all modifications from that point. From that point of view, I actually don't much care whether we use submodule or monolithic repository at this stage.

**Pull request merged**
