### PR TITLE
Imager model file update for level-3 ICD drafts for LPDP

### PR DESCRIPTION
**Pull request by tnakamot**
Changes made for Level-3 ICD drafts for LPDP. Comments at IRIS Software Meeting on 2016-08-15 are reflected.

### CODE REVIEW

**Comment by edwardchapin** [comment]
@tnakamot: I did a local test merge of this pull request with the one I still have pending (#6) and it didn't complain about any conflicts. However, it may still have an impact (e.g., assembly names changing to include the `sci-` prefix etc.) which will require some careful checking throughout. I'd like to hold-off on applying your current merge request until we get #6 released as it will be the simplest, literal translation of the existing word document TCS-to-IRIS ICD (and hopefully these easiest to test/debug the entire process). Does that sound reasonable?

**Comment by jasonweiss** [comment]
this is a large amount of changes.  i'm inclined to simply merge, and then review the result.

**Comment by tnakamot** [comment]
@edwardchapin I already merged your tcs-to-iris-initial branch into imager-level3-lpdp branch, and actually this pull request already includes your changes. Because your pull request on #6 only includes 2 commits, I just made double-check now and confirmed that your literal translation from TCS-IRIS ICD still remains in this pull request.

@jasonweiss I think you can first merge #6, and then #7 which would just become fast-forward merge and cause no conflict.

**Comment by edwardchapin** [comment]
@tnakamot yes, you are quite right regarding your inclusion of the tcs-to-iris-initial branch. I do notice one problem though - the pull request on the TCS side that goes with #6 subscribes to odgwShift in the previously-named "imager-adc-assembly" assembly, so it breaks the ICD. It would be a fairly trivial change to my [TCS pull request](https://github.com/chrisaj5/TCS-Model-Files/pull/1) to make it compatible with this change, although it starts to get quite confusing! As a process, I think it's a good idea to deal with one block of changes at a time (i.e., serialize application of related pull requests), to prepare for when we have much more complicated changes happening. Unfortunately we don't have any automated way to check for these "broken links".

**Comment by jasonweiss** [comment]
i want to get these commits into the master to review.  i'm hoping reviewing the generated files will be easier than looking at hocom.  please report problems on the issue tracker for this repo.  (which is..... where?)

**Comment by tnakamot** [comment]
@edwardchapin I think the problem is that icd tools do not show any warning for "broken links" when they ingest model files. Broken links should be detected automatically not just for this kind of incompatible change issues, but also for typo.

**Comment by tnakamot** [comment]
@edwardchapin I filed a feature request for detecting "broken links" here https://github.com/tmtsoftware/icd/issues/35.

**Pull request merged**
