### PR TITLE
Walth initial

### PR DESCRIPTION
**Pull request by gwalth**
Adding the DRS subscribe model files for telemetry data necessary for the FITS header metadata.

### CODE REVIEW

**Comment by jasonweiss** [comment]
Greg, have you tried ingesting this into the ICD-DB?  i see syntax not specified in the API, like component. 

Your telemetry item names need to match the system kim is using with prefixes consisting of the system and component name.  i suggest you put the FITS name in usage with a indicator tag that it's a fit header keyword, such as "FITS=<KWNAME>" or whatever makes sense to you.

**Comment by jasonweiss** [comment]
to clarify, 

{
   subsystem =  IRIS
   component =  IMG.FILT
   name =  FILTPOS
   requiredRate =  1
   usage = "Filter position"
 }

becomes:

{
   subsystem =  IRIS
   name =  iris.sci-filter-assembly.filter
   requiredRate =  1
   usage = "Filter position.  FITS=FILTPOS"
 +}

**Comment by tnakamot** [comment]
@jasonweiss In terms of syntax, Greg is correct. Without "component" attribute in the subscribed item, latest version of icd-db tools in master branch complains like below:

`error: drs/drs-assembly/subscribe-model.conf, at path: /subscribe/telemetry/67: error: object has missing required properties (["component"]) (schema: config:/subscribe-info-schema.conf#:)`

[Examples](https://github.com/tmtsoftware/icd/tree/master/examples) also have "component" attribute. So, I think ICD users manual should be updated.

**Comment by tnakamot** [comment]
@gwalth For component names, and telemetry names of IRIS subsystems, please take a look at the latest version of model files and your subscribe-model.conf should contain the same name. For example, [the component name of filter is "sci-filter-assembly", and the filter name can be obtained as an attribute of "filter" telemetry](https://github.com/gwalth/IRIS-Model-Files/blob/master/imager/filter-assembly/publish-model.conf), so the corresponding subscribed item should look like below:

> {
> subsystem = IRIS
> component = sci-filter-assembly
> name = filter
> requiredRate = 1
> usage = "(as you want)"
> }

Other than the name issues, I have some questions specifically related to Imager.
- What do you actually want by "filter position"? There will be 5 filter wheels in the filter assembly in Imager. Do you to want to know the individual position of each filter? If so, in what unit in which coordinate? It could be raw stepper motor steps, or rotation angle, or even position name. But, my gut feeling says you would finally want to obtain throughput information as a function of wavelength. If so, "throughput" telemetry is the right one, though the number of array elements (= resolution of wavelength) is not determined yet.
- What do you expect from "detector name"? If you expect a static string like "detector 1", I think this information doesn't have to be exchanged over telemetry service.
- Detector gain is currently defined as [IRIS.imager-detector-assembly.gain](https://github.com/gwalth/IRIS-Model-Files/blob/master/imager/detector-assembly/publish-model.conf) as 4 elements array. Each element corresponds to one detector gain.
- What do you expect from "detector noise"? There are several types of noise...
- Detector temperature is maintained by [IRIS.cryotemp-assembly](https://github.com/gwalth/IRIS-Model-Files/blob/master/sc/cryotemp-assembly/component-model.conf) in the current design.
- Don't you need information from [ADC](https://github.com/gwalth/IRIS-Model-Files/blob/master/imager/adc-assembly/publish-model.conf) and [cold stop](https://github.com/gwalth/IRIS-Model-Files/blob/master/imager/coldstop-assembly/publish-model.conf) as they are also inserted to the light path, and affects the quality of science frames.

**Comment by jasonweiss** [comment]
re: component attribute. ok, cool, i was just going off the documentation, but having that tag probably simplifies it a bit.

**Comment by gwalth** [comment]
@tnakamot Thanks for your feedback, it has been helpful to move the DRS model files along. 

Here my responses to your comments:
- For the filter position, the DRS needs to support both science and engineering and it is necessary to know which filters are in which position slot name (e.g. J-band filter in filter slot #2).  With 5 filter wheels, we will probably need to know which wheel and position in the wheel (i.e. Wheel # 2, filter slot position #3).
- For the detector name, the DRS needs to keep track or two things; (1) which detector goes with which gain/read noise/etc and (2) the type of detector, specifically if the detector changes (i.e H4RGv1 --> H4RGv2), so that the pipeline can reduce past and present data.
- For the detector noise, it was suppose to say detector read noise.
- ADC and cold stop are needed, we hadn't added them yet, but thanks for reminding us.

**Comment by gwalth** [comment]
@jasonweiss In addition to our discussion about the IRIS.cryotemp-assembly, the DRS will obviously require temperature sensors throughout the IRIS dewar.

I think the scheme you setup should work fine, we just want to make sure we have enough sensors for the DRS.

Here is a rough layout of where we anticipate temperature sensors:
* 16 temperature sensors
   * 8 imager
   * 8 spectrograph
      * 4 optical bench
      * 2 shields
      * 2 for thermal gradients

Anywhere there is a moving mechanism, we should probably have a temperature sensor (i.e. filter wheel, grating,...).

**Comment by tnakamot** [comment]
@gwalth No problem. I also want to make sure what is needed to make Imager design move forward. , so it is good to make this kind of iteration.

- To convey filter information, there are several ways to do that. For example, the filter assembly can publish a telemetry item of filter name (and probably with throughput information) instead of filter slot number, so that DRS doesn't have to know which filters are in which position slot name.
- Don't we have to take into account the case where more than one filter are inserted (e.g. ND filter in wheel 1 + J filter in wheel 2)?
- As written in my draft of IMG-DRS ICD, the detector numbering is fixed. So, by subscribing "gain" telemetry (this is 4 element array), DRS will be able to know which detector uses which gain.
- Thanks for reminding me of the case for changing detectors should be considered. What if Imager provides serial number of each detector as a part of some telemetry? Intrinsically, the detector does not have any name, but serial number.
- Ryuji pointed me out that the version of software related to detector controlling would be convenient for debugging purposes, I put this information in a telemetry of detector assembly. This would be more frequently changed than the detector itself.
- Detector read noise: let me ask what is it used for in DRS. The read noise for each detector would be measured at commissioning phase to evaluate the performance of the imager detectors, but the read noise would be different among channels (there will be 64 channels per detector), or even pixels. Is that what you want?

**Pull request merged**
