### PR TITLE
Walth component update

### PR DESCRIPTION
**Pull request by gwalth**
Updated Imager and IFS components and functions for the subscribe model file for the DRS assembly.

### CODE REVIEW

**Comment by jasonweiss** [comment]
Greg said he is going to do a few more commits before this PR should be merged.  Greg, just let us know when we should take another look at this, or close this and submit another PR.

**Comment by jasonweiss** [comment]
i have some more comments and edits, but it's a good pass at this and i think we should and apply my comments to another PR.

my main issue is that the component names don't match what the other subsystems are using.  i know that for many external systems, we don't know the component names, but for IRIS we should use the component names we are using in our model files.

so for example, instead of

{
  subsystem =  IRIS
  component =  ifs-detector-assembly.currentConfig
  name =  intergrationTime
  requiredRate =  1
  usage = "IFS integration time of each readout. FITS=ITIME"
}

{
  subsystem =  IRIS
  component =  ifs-detector-assembly.currentConfig
  name =  reads
  requiredRate =  4
  usage = "Total number of IFS readouts in this ramp. FITS=READS"
}

we could have:

{
  subsystem =  IRIS
  component =  ifs-detector-assembly
  name =  currentConfig
  requiredRate =  4
  usage = '''
     Current exposure configuration.  Contains the following:
           * integrationTime: IFS integration time of each readout. FITS=ITIME
           * reads: Total number of IFS readouts in this ramp. FITS=READS
      etc...
     """
}

then we use the model files to ensure that we have an agreement on each side.  if you need something from say the ifs detector assembly we aren't currently providing (e.g. gain), we will then add it to reconcile.  

i think we want to do this for all external subsystems, too, by contacting the owners of those subsystem model files, or making those model files ourselves if they aren't being constructed by anyone.

**Comment by tnakamot** [comment]
For the imager parts, based on the modification in DRS model files in this pull request and also a list of metadata that DRS wants to get from the imager (Greg sent me yesterday), I catch what DRS wants to know. So, based on that, I am now editing model files for the imager and also DRS if necessary in a separate branch img-drs-lpdp. If Jason merges this pull request, then I will make another pull request for img-drs-lpdp. Or, that branch can be merged to this pull request if you want (I'm flexible on that). In any case, others (at least, Jason and Greg) will have a chance to review.

Greg, btw, in your last commit, the commit comment says "Also, script that generates model files now sorts so git differences will be easier to see." This is really nice. If possible, could you share also this script with us? I think you can probably put it in the same directly as the model files, then I can run the same script when I edit DRS model file.

**Comment by tnakamot** [comment]
Jason, very very trivial comment: by inserting an empty line before the bullet list, it is actually recognized as a start of the list, and converted to <li> list by icd-db tools so the list looks nice in, at least, icd-web, and also in the generated PDF (though I haven't checked it). So, for the subscription to a telemetry item which may contains several metadata variables in it, the usage field could be

usage = '''
Current exposure configuration. Contains the following:

* integrationTime: IFS integration time of each readout. FITS=ITIME
* reads: Total number of IFS readouts in this ramp. FITS=READS
etc...
"""

Other than that, I like this idea. It is really good to mention what variable corresponds to what FITS header.

**Pull request merged**
