### PR TITLE
Commands for DRS assembly, update of IS commands, update of DRS subscribe model

### PR DESCRIPTION
**Pull request by jasonweiss**
these changes deal with trying to cleanup all of the subscribe items that deal with the instrument, particularly the IRIS.is items.  many of them are moved to commands sent from ESW via IS to DRS, and therefore removed from the subscription model.  the one major outstanding IRIS item that is not quite formatted correctly is the CSRO stuff.

Greg, i made quite a few changes to the subscribe model so i'd expect that it'd break your script... or at least, running your script would vastly undo the work ji man and i did to get the subscribe model compatible with the other publish model files.  please take a look at what we did and decide whether to modify your script, or disregard it, if what we've produced is far enough along it can just be edited by hand.

### CODE REVIEW

**Comment by jasonweiss** [comment]
Sorry guys, forgot to validate... i'll do that now...

**Comment by jasonweiss** [comment]
ok, validated... comments welcome.  want to close by 5pm today if possible.  let me know if you need more time.

**Comment by jimansohn** [comment]
Looks fine by me

**Comment by gwalth** [comment]
Thanks for cleaning the model files!  It will definitely break my script, it's not setup to handle the attributes yet.  I'll have to do them all by hand.  Just to double check, most of the changes were done in the weiss-ici branch?

**Comment by gwalth** [comment]
I think it looks good enough merge if you want to do that and I can make the other changes.

**Comment by jasonweiss** [comment]
yes, weiss-ici branch

**Pull request merged**
